export const ALL_PROPERTIES_SUCCESS = "ALL_PROPERTIES_SUCCESS";
export const ALL_PROPERTIES_FAIL = "ALL_PROPERTIES_FAIL";

export const PROPERTIES_DETAILS_SUCCESS = "PROPERTIES_DETAILS_SUCCESS";
export const PROPERTIES_DETAILS_FAIL = "PROPERTIES_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
