export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOAD_TRAVELLER_SUCCESS = "LOAD_TRAVELLER_SUCCESS";
export const LOAD_TRAVELLER_REQUEST = "LOAD_TRAVELLER_REQUEST";
export const LOAD_TRAVELLER_FAIL = "LOAD_TRAVELLER_FAIL";

export const UPDATE_PROFILE_SUCCESS = " UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_REQUEST = " UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_RESET = " UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = " UPDATE_PROFILE_FAIL";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
